---
title: "Practical_gbif"
author: "Jan Schwalb"
date: "25/05/2020"
output: html_document
---

```{r}
##install package
install.packages(c("tidyverse", "rgbif", "sp", "countrycode", "CoordinateCleaner", "data.table", "rgdal", "rgeos"))
```


```{r}
## load library
library(tidyverse)
library(rgbif)
library(sp)
library(countrycode)
library(CoordinateCleaner)
library(data.table)
library(rgdal)
library(rgeos)
```


```{r }
##search for occurence records and explore data
objectdata<-occ_search(scientificName = "Ceiba pentandra",
                       return = "data", limit = 500)

##number of records
nrow(objectdata)
names(objectdata)
plot(objectdata$decimalLatitude~objectdata$decimalLongitude)
```

```{r}
##use the suggest function to get gbif taxon key
tax_key<-name_suggest(q="Ceiba",rank="Genus")
tax_key

##becaus there are different key numbers check how many entrys are availabe
lapply(tax_key$key,"occ_count")

##choose taxon key
tax_key<-tax_key$key[1]
```

What if i want a record from a country
```{r}
occ_count(tax_key,country = "BR")
```

use coordinates
```{r}
study_area<-"POLYGON((-35 -4.5, -38.5 -4.5, -38.5 -7, -35 -7, -35 -4.5))"

datasa<-occ_search(taxonKey = tax_key, return = "data",hasCoordinate = TRUE, geometry = study_area)
```

```{r}
gen_list<- c("Ceiba","Eriotheca")
tax_keylist <- lapply(gen_list, function(k) {name_suggest(c=k, rank = "Genus")})
 
##get all the taxonkeys from list 
new <- unlist(lapply(tax_keylist,"[[","key"))

##search
data_gel<-occ_search(taxonKey = new,return = "data",hasCoordinate = TRUE,country = "BR")

```

download and save the data
```{r}
data_final<-lapply(data_gel,"as.data.frame")
a <- bind_rows(data_final)
write.csv(a,"gbif_occ.csv")
```

